# Site settings
title: Pre-MAP Fall 2015
email: garofali@uw.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/Pre-MAP/" # the subpath of your site, e.g. /blog/
url: "http://kgarofali.github.io/Pre-MAP" # the base hostname & protocol for your site
premap_home: "http://www.astro.washington.edu/users/premap/"


# Build settings
markdown: kramdown
